"""add adversarial test reports table

Revision ID: 1daa5ff1d174
Revises: fbc2877b4ee2
Create Date: 2026-09-22 21:55:32.946699

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = '1daa5ff1d174'
down_revision: Union[str, None] = 'fbc2877b4ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adversarial_test_reports',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('worst_case_max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('worst_case_net_return_pct', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('failure_reasons', sa.JSON(), nullable=False),
    sa.Column('scenario_breakdown', sa.JSON(), nullable=False),
    sa.Column('robustness_score', sa.Float(), nullable=False),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adversarial_test_reports')
    # ### end Alembic commands ###
