"""add regime validation reports table

Revision ID: 3541f9dd59d4
Revises: e9139983d462
Create Date: 2026-09-22 21:41:58.841903

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = '3541f9dd59d4'
down_revision: Union[str, None] = 'e9139983d462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_validation_reports',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('per_regime', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('classification_reasoning', sa.JSON(), nullable=False),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regime_validation_reports')
    # ### end Alembic commands ###
