"""initial schema

Revision ID: 961c3ba1bb6b
Revises: 
Create Date: 2026-09-21 01:22:11.390798

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '961c3ba1bb6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('council_decisions',
    sa.Column('market_candle_open_time', sa.BigInteger(), nullable=False),
    sa.Column('market_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consensus_bias', sa.String(length=16), nullable=False),
    sa.Column('consensus_confidence', sa.Float(), nullable=False),
    sa.Column('vote_tally', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('judge_invoked', sa.Boolean(), nullable=False),
    sa.Column('judge_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_bias', sa.String(length=16), nullable=False),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('key_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalidators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generations',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('population_target', sa.Integer(), nullable=False),
    sa.Column('population_created', sa.Integer(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('total_capital_allocated', sa.Float(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=4096), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('market_candles',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('funding_rate', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'open_time', name='uq_candle_symbol_tf_time')
    )
    op.create_index('ix_candle_symbol_tf_time', 'market_candles', ['symbol', 'timeframe', 'open_time'], unique=False)
    op.create_table('market_features',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('candle_open_time', sa.BigInteger(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'candle_open_time', name='uq_features_symbol_tf_time')
    )
    op.create_index('ix_features_symbol_tf_time', 'market_features', ['symbol', 'timeframe', 'candle_open_time'], unique=False)
    op.create_table('market_regimes',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('candle_open_time', sa.BigInteger(), nullable=False),
    sa.Column('regime', sa.Enum('TREND_UP', 'TREND_DOWN', 'RANGE', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'BREAKOUT', 'BREAKDOWN', 'UNCERTAIN', name='market_regime_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detector_version', sa.String(length=16), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'candle_open_time', name='uq_regime_symbol_tf_time')
    )
    op.create_index('ix_regime_symbol_tf_time', 'market_regimes', ['symbol', 'timeframe', 'candle_open_time'], unique=False)
    op.create_table('population_events',
    sa.Column('event_type', sa.Enum('GENERATION_CREATED', 'POPULATION_EXTINCT', 'POPULATION_REBUILT', 'MILESTONE_REACHED', name='population_event_type_enum'), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('population_status', sa.Enum('ACTIVE', 'EXTINCT', 'REBUILDING', name='population_status_enum'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('family', sa.Enum('MOMENTUM', 'TREND_FOLLOWING', 'BREAKOUT', 'MEAN_REVERSION', 'VOLATILITY', 'MARKET_STRUCTURE', 'VWAP', 'SCALPING', 'ORDER_FLOW', 'HYBRID', name='strategy_family_enum'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_events',
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='system_event_severity_enum'), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('council_analyses',
    sa.Column('council_decision_id', sa.UUID(), nullable=False),
    sa.Column('analyst', sa.String(length=32), nullable=False),
    sa.Column('bias', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=4096), nullable=False),
    sa.Column('key_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalidators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('was_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['council_decision_id'], ['council_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_strategy_version_id', sa.UUID(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('mutation_id', sa.UUID(), nullable=True),
    sa.Column('dna', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.Enum('RESEARCH', 'BACKTEST', 'WALK_FORWARD', 'OUT_OF_SAMPLE', 'PAPER', 'SHADOW', 'SMALL_LIVE', 'APPROVED_LIVE', 'REJECTED', name='strategy_stage_enum'), nullable=False),
    sa.Column('champion_status', sa.Enum('CHAMPION', 'CHALLENGER', 'RETIRED', 'REJECTED', name='champion_status_enum'), nullable=True),
    sa.Column('hypothesis', sa.String(length=4096), nullable=False),
    sa.Column('proposed_by', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_strategy_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version')
    )
    op.create_table('agents',
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DEAD', name='agent_status_enum'), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('funding_paid', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_professional', sa.Boolean(), nullable=False),
    sa.Column('best_milestone_multiple', sa.Float(), nullable=False),
    sa.Column('death_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('death_reason', sa.String(length=256), nullable=True),
    sa.Column('final_equity', sa.Float(), nullable=True),
    sa.Column('final_pnl', sa.Float(), nullable=True),
    sa.Column('fitness', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('evolution_events',
    sa.Column('event_type', sa.Enum('MUTATION', 'CROSSOVER', 'NOVEL_GENERATION', 'PROMOTION', 'REJECTION', 'DIVERSITY_INJECTION', name='evolution_event_type_enum'), nullable=False),
    sa.Column('parent_strategy_version_id', sa.UUID(), nullable=True),
    sa.Column('parent_strategy_version_id_2', sa.UUID(), nullable=True),
    sa.Column('child_strategy_version_id', sa.UUID(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.String(length=4096), nullable=False),
    sa.Column('ollama_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_strategy_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_strategy_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_strategy_version_id_2'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_snapshots',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('strategy_dna', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indicator_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regime_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('software_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitness_scores',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=False),
    sa.Column('return_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('robustness_score', sa.Float(), nullable=False),
    sa.Column('oos_score', sa.Float(), nullable=False),
    sa.Column('drawdown_penalty', sa.Float(), nullable=False),
    sa.Column('instability_penalty', sa.Float(), nullable=False),
    sa.Column('weights_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='order_side_enum'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('venue', sa.Enum('PAPER', 'SHADOW', 'LIVE', name='execution_venue_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REDUCED', 'REJECTED', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'FAILED', name='order_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=256), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_venue_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_table('performance_metrics',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('loss_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('average_trade', sa.Float(), nullable=True),
    sa.Column('average_winner', sa.Float(), nullable=True),
    sa.Column('average_loser', sa.Float(), nullable=True),
    sa.Column('largest_win', sa.Float(), nullable=True),
    sa.Column('largest_loss', sa.Float(), nullable=True),
    sa.Column('consecutive_wins', sa.Integer(), nullable=True),
    sa.Column('consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('sharpe_like', sa.Float(), nullable=True),
    sa.Column('sortino_like', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('average_holding_seconds', sa.Float(), nullable=True),
    sa.Column('survival_seconds', sa.Float(), nullable=False),
    sa.Column('regime_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('oos_score', sa.Float(), nullable=True),
    sa.Column('walk_forward_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='position_side_enum'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('trailing_stop_distance', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('entry_order_id', sa.UUID(), nullable=True),
    sa.Column('exit_order_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='trade_side_enum'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('funding', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('holding_seconds', sa.Integer(), nullable=False),
    sa.Column('entry_regime', sa.String(length=32), nullable=True),
    sa.Column('exit_regime', sa.String(length=32), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['entry_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['exit_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('council_decision_id', sa.UUID(), nullable=True),
    sa.Column('market_candle_open_time', sa.BigInteger(), nullable=False),
    sa.Column('market_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_signal', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='decision_signal_enum'), nullable=False),
    sa.Column('agent_signal_confidence', sa.Float(), nullable=False),
    sa.Column('agent_signal_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_decision', sa.Enum('APPROVED', 'REDUCED', 'REJECTED', name='decision_risk_enum'), nullable=False),
    sa.Column('risk_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['council_decision_id'], ['council_decisions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # orders.decision_id -> decisions.id is added here, after both tables
    # exist, to break the orders<->decisions circular FK dependency
    # (Order references Decision via decision_id, Decision references Order
    # via order_id). Autogenerate emits this constraint inline on
    # create_table('orders', ...) with use_alter=True, but Alembic's
    # per-table op.create_table does NOT replicate SQLAlchemy
    # MetaData.create_all()'s deferred-FK handling — the constraint would
    # silently never be created without this explicit call.
    op.create_foreign_key(
        "fk_orders_decision_id", "orders", "decisions", ["decision_id"], ["id"]
    )


def downgrade() -> None:
    # The use_alter FK must be dropped before 'orders' or 'decisions' can be
    # dropped below.
    op.drop_constraint("fk_orders_decision_id", "orders", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_table('trades')
    op.drop_table('positions')
    op.drop_table('performance_metrics')
    op.drop_table('orders')
    op.drop_table('fitness_scores')
    op.drop_table('agent_snapshots')
    op.drop_table('evolution_events')
    op.drop_table('agents')
    op.drop_table('strategy_versions')
    op.drop_table('council_analyses')
    op.drop_table('system_events')
    op.drop_table('strategies')
    op.drop_table('population_events')
    op.drop_index('ix_regime_symbol_tf_time', table_name='market_regimes')
    op.drop_table('market_regimes')
    op.drop_index('ix_features_symbol_tf_time', table_name='market_features')
    op.drop_table('market_features')
    op.drop_index('ix_candle_symbol_tf_time', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_table('generations')
    op.drop_table('council_decisions')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for Postgres native enums, which
    # otherwise leaves orphaned types behind and breaks a subsequent
    # `upgrade` with "type already exists". Drop them explicitly here.
    for enum_name in (
        "agent_status_enum",
        "champion_status_enum",
        "decision_risk_enum",
        "decision_signal_enum",
        "evolution_event_type_enum",
        "execution_venue_enum",
        "market_regime_enum",
        "order_side_enum",
        "order_status_enum",
        "population_event_type_enum",
        "population_status_enum",
        "position_side_enum",
        "strategy_family_enum",
        "strategy_stage_enum",
        "system_event_severity_enum",
        "trade_side_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
