"""add council quorum and timing audit columns

Revision ID: b9bae753da23
Revises: defb64bc9372
Create Date: 2026-09-22 22:46:33.896211

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = 'b9bae753da23'
down_revision: Union[str, None] = 'defb64bc9372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('council_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True))

    # server_default backfills existing rows (97 in dev) as if they were a
    # healthy full 8/8 council — the best honest default for historical
    # data predating this audit trail, since we have no record of what
    # actually happened for those cycles.
    with op.batch_alter_table('council_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('council_status', sa.String(length=16), nullable=False, server_default='COMPLETE'))
        batch_op.add_column(sa.Column('expected_analysts', sa.Integer(), nullable=False, server_default='8'))
        batch_op.add_column(sa.Column('successful_analysts', sa.Integer(), nullable=False, server_default='8'))
        batch_op.add_column(sa.Column('failed_analysts', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('failure_reasons', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('quorum_met', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('trade_allowed', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('council_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_council_latency_seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('council_decisions', schema=None) as batch_op:
        batch_op.drop_column('total_council_latency_seconds')
        batch_op.drop_column('council_start')
        batch_op.drop_column('trade_allowed')
        batch_op.drop_column('quorum_met')
        batch_op.drop_column('failure_reasons')
        batch_op.drop_column('failed_analysts')
        batch_op.drop_column('successful_analysts')
        batch_op.drop_column('expected_analysts')
        batch_op.drop_column('council_status')

    with op.batch_alter_table('council_analyses', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
