"""add challenger evaluations table

Revision ID: defb64bc9372
Revises: f8d88d7688c6
Create Date: 2026-09-22 22:20:31.243437

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = 'defb64bc9372'
down_revision: Union[str, None] = 'f8d88d7688c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenger_evaluations',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=32), nullable=False),
    sa.Column('entered_stage_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('min_observation_days_required', sa.Integer(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=False),
    sa.Column('blocking_reasons', sa.JSON(), nullable=False),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenger_evaluations')
    # ### end Alembic commands ###
