"""add trade stage column

Revision ID: e9139983d462
Revises: 1410d7b79d55
Create Date: 2026-09-22 21:29:31.367278

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9139983d462'
down_revision: Union[str, None] = '1410d7b79d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.Enum('RESEARCH', 'BACKTEST', 'WALK_FORWARD', 'OUT_OF_SAMPLE', 'PAPER', 'SHADOW', 'SMALL_LIVE', 'APPROVED_LIVE', 'REJECTED', name='trade_stage_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
