"""add trade stage column

Revision ID: e9139983d462
Revises: 1410d7b79d55
Create Date: 2026-09-22 21:29:31.367278

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9139983d462'
down_revision: Union[str, None] = '1410d7b79d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TRADE_STAGE = sa.Enum('RESEARCH', 'BACKTEST', 'WALK_FORWARD', 'OUT_OF_SAMPLE', 'PAPER', 'SHADOW', 'SMALL_LIVE', 'APPROVED_LIVE', 'REJECTED', name='trade_stage_enum')


def upgrade() -> None:
    # PostgreSQL needs the native enum TYPE to exist before a column can use it
    # (SQLite has no native enums, so this is a no-op there).
    _TRADE_STAGE.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', _TRADE_STAGE, nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('stage')
    _TRADE_STAGE.drop(op.get_bind(), checkfirst=True)
