"""add strategy correlation tables

Revision ID: f8d88d7688c6
Revises: 1daa5ff1d174
Create Date: 2026-09-22 22:11:21.762874

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = 'f8d88d7688c6'
down_revision: Union[str, None] = '1daa5ff1d174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_convergence_snapshots',
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('population_diversity_score', sa.Float(), nullable=False),
    sa.Column('mean_pairwise_correlation', sa.Float(), nullable=False),
    sa.Column('pct_agents_above_max_correlation', sa.Float(), nullable=False),
    sa.Column('family_distribution', sa.JSON(), nullable=False),
    sa.Column('diversity_pressure_applied', sa.Boolean(), nullable=False),
    sa.Column('actions_taken', sa.JSON(), nullable=False),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_family_correlations',
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('family_a', sa.String(length=32), nullable=False),
    sa.Column('family_b', sa.String(length=32), nullable=False),
    sa.Column('mean_correlation', sa.Float(), nullable=False),
    sa.Column('member_pair_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_correlations',
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('agent_id_a', sa.Uuid(), nullable=False),
    sa.Column('agent_id_b', sa.Uuid(), nullable=False),
    sa.Column('strategy_family_a', sa.String(length=32), nullable=False),
    sa.Column('strategy_family_b', sa.String(length=32), nullable=False),
    sa.Column('dna_similarity', sa.Float(), nullable=False),
    sa.Column('feature_similarity', sa.Float(), nullable=False),
    sa.Column('entry_condition_similarity', sa.Float(), nullable=False),
    sa.Column('exit_condition_similarity', sa.Float(), nullable=False),
    sa.Column('trade_direction_correlation', sa.Float(), nullable=True),
    sa.Column('return_correlation', sa.Float(), nullable=True),
    sa.Column('position_overlap', sa.Float(), nullable=True),
    sa.Column('trade_timing_similarity', sa.Float(), nullable=True),
    sa.Column('composite_correlation', sa.Float(), nullable=False),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id_a'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_id_b'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_correlations')
    op.drop_table('strategy_family_correlations')
    op.drop_table('correlation_convergence_snapshots')
    # ### end Alembic commands ###
