"""add reality gap fields and reality_gap_reports table

Revision ID: fbc2877b4ee2
Revises: 3541f9dd59d4
Create Date: 2026-09-22 21:49:11.097546

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = 'fbc2877b4ee2'
down_revision: Union[str, None] = '3541f9dd59d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reality_gap_reports',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('stages_present', sa.JSON(), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('cumulative_gap', sa.JSON(), nullable=True),
    sa.Column('computed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latency_ms', sa.Integer(), nullable=True))

    with op.batch_alter_table('stage_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_funding', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_slippage_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_trade_net_pnl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_latency_ms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('missed_trade_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('missed_trade_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_signal_to_fill_seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_metrics', schema=None) as batch_op:
        batch_op.drop_column('avg_signal_to_fill_seconds')
        batch_op.drop_column('missed_trade_pct')
        batch_op.drop_column('missed_trade_count')
        batch_op.drop_column('avg_latency_ms')
        batch_op.drop_column('avg_trade_net_pnl')
        batch_op.drop_column('total_slippage_cost')
        batch_op.drop_column('total_funding')
        batch_op.drop_column('total_fees')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('latency_ms')

    op.drop_table('reality_gap_reports')
    # ### end Alembic commands ###
